// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLwaF4_KdW1gFPB1Fn4hBpYkIpszwwDCU',
    appId: '1:431844355119:web:e9100ad62f5ebcd931eada',
    messagingSenderId: '431844355119',
    projectId: 'labor-6795c',
    authDomain: 'labor-6795c.firebaseapp.com',
    storageBucket: 'labor-6795c.appspot.com',
    measurementId: 'G-P16X6LK3WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF4vnXQAY7SXchi8otDQRqBX5jKm4CL1Q',
    appId: '1:431844355119:android:24192e6e3fbdb5de31eada',
    messagingSenderId: '431844355119',
    projectId: 'labor-6795c',
    storageBucket: 'labor-6795c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Q9qVjOtkAS8ELLJ-JD9tuAA75B9eIws',
    appId: '1:431844355119:ios:e647f494495487ef31eada',
    messagingSenderId: '431844355119',
    projectId: 'labor-6795c',
    storageBucket: 'labor-6795c.appspot.com',
    iosClientId: '431844355119-l9n0stgafmj5r2rk45nc1389svoj4em4.apps.googleusercontent.com',
    iosBundleId: 'com.example.laborApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Q9qVjOtkAS8ELLJ-JD9tuAA75B9eIws',
    appId: '1:431844355119:ios:6c26f93e4582049f31eada',
    messagingSenderId: '431844355119',
    projectId: 'labor-6795c',
    storageBucket: 'labor-6795c.appspot.com',
    iosClientId: '431844355119-34ftd65ptor91cne1a2rh9kdj82laq36.apps.googleusercontent.com',
    iosBundleId: 'com.example.laborApp.RunnerTests',
  );
}
